const baseUrl = import.meta.env.VITE_SUPABASE_URL;
const publicKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const list = document.querySelector("#raffles"); const detail = document.querySelector("#raffle-detail"); const modal = document.querySelector("#raffle-dialog"); const participation = document.querySelector("#participation-dialog"); const participationContent = document.querySelector("#participation-content");
let raffles = []; let selected = []; let active = null; let reservation = null;
const money = new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const safe = (value) => String(value || "");
const escapeHtml = (value) => safe(value).replace(/[&<>'"]/g, (character) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"})[character]);
async function api(method, body) { if (!baseUrl || !publicKey) throw new Error("El módulo aún no está configurado."); const response = await fetch(`${baseUrl}/functions/v1/raffle-public`,{method,headers:{apikey:publicKey,"content-type":"application/json"},body:body?JSON.stringify(body):undefined}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||"No fue posible completar la solicitud"); return data; }
async function upload(kind, file) { if (!(file instanceof File) || !file.size) return null; const body = new FormData(); body.set("reservationId", reservation.id); body.set("reservationCode", reservation.code); body.set("kind", kind); body.set("file", file); const response = await fetch(`${baseUrl}/functions/v1/raffle-file-upload`, { method: "POST", headers: { apikey: publicKey }, body }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "No fue posible cargar el archivo"); return data; }
function statusLabel(status){return({upcoming:"Próximamente",active:"Activo",sold_out:"Agotado",finished:"Finalizado"})[status]||status}
function card(raffle){const node=document.createElement("article");node.className="raffle-card";if(raffle.prizeImageUrl){const image=document.createElement("img");image.src=raffle.prizeImageUrl;image.alt=raffle.prizeName;node.append(image)}const copy=document.createElement("div");copy.innerHTML=`<span class="status">${escapeHtml(statusLabel(raffle.status))}</span><h2>${escapeHtml(raffle.title)}</h2><p>${escapeHtml(raffle.description)}</p><div class="stats"><span><b>${money.format(raffle.priceCop)}</b>por número</span><span><b>${raffle.availableCount}</b>disponibles</span><span><b>${raffle.participantCount}</b>participantes</span></div>`;const show=document.createElement("button");show.className="primary";show.textContent="Ver números disponibles";show.onclick=()=>openRaffle(raffle);copy.append(show);node.append(copy);return node}
function render(){list.replaceChildren(...raffles.map(card));if(!raffles.length)list.append(document.querySelector("#empty-template").content.cloneNode(true))}
function openRaffle(raffle){active=raffle;selected=[];reservation=null;detail.replaceChildren();const title=document.createElement("h2");title.textContent=raffle.title;const info=document.createElement("p");info.className="notice";info.textContent=`Selecciona hasta ${raffle.maxNumbersPerParticipant} números. El pago se valida manualmente; abrir Nequi no confirma tu participación.`;const grid=document.createElement("div");grid.className="number-grid";raffle.numbers.forEach(item=>{const b=document.createElement("button");b.type="button";b.className=`number ${item.state}`;b.textContent=String(item.number).padStart(2,"0");b.disabled=item.state!=="available";b.onclick=()=>{if(selected.includes(item.number))selected=selected.filter(n=>n!==item.number);else if(selected.length<raffle.maxNumbersPerParticipant)selected.push(item.number);renderNumbers()};grid.append(b)});const total=document.createElement("p");total.id="selection-total";const proceed=document.createElement("button");proceed.className="primary";proceed.textContent="Participar";proceed.onclick=reserve;detail.append(title,info,grid,total,proceed);renderNumbers();modal.showModal()}
function renderNumbers(){detail.querySelectorAll(".number").forEach(button=>button.classList.toggle("selected",selected.includes(Number(button.textContent))));const total=detail.querySelector("#selection-total");total.textContent=selected.length?`${selected.length} número(s): ${money.format(selected.length*active.priceCop)}`:"Selecciona uno o más números.";detail.querySelector(".primary").disabled=!selected.length}
async function reserve(){try{const data=await api("POST",{action:"reserve",raffleId:active.id,numbers:selected,website:""});reservation=data.reservation;modal.close();openForm()}catch(error){alert(error.message);await load()}}
function openForm(){participationContent.innerHTML=`<h2>Completa tu participación</h2><p class="notice">Tus números quedan reservados hasta ${new Date(reservation.expiresAt).toLocaleTimeString("es-CO",{hour:"2-digit",minute:"2-digit"})}. Total: <b>${money.format(selected.length*active.priceCop)}</b>.</p><form id="participant-form" class="form-stack"><div class="form-grid"><label>Nombre completo<input name="fullName" maxlength="140" required></label><label>Teléfono<input name="phone" inputmode="tel" maxlength="32" required></label></div><div class="form-grid"><label>Correo (opcional)<input name="email" type="email" maxlength="254"></label><label>Ciudad (opcional)<input name="city" maxlength="100"></label></div><div class="form-grid"><label>Foto del participante (opcional)<input name="participantPhoto" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Comprobante de pago<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp" required></label></div><label>Referencia de pago (opcional)<input name="paymentReference" maxlength="120"></label><div class="form-grid"><label>Valor reportado<input name="reportedAmount" type="number" min="0" step="1" value="${selected.length*active.priceCop}"></label><label>Fecha del pago<input name="paidAt" type="date"></label></div><label>Observaciones (opcional)<textarea name="observations" maxlength="1000"></textarea></label><label class="check"><input name="consent" type="checkbox" required><span>${escapeHtml(active.privacyText)} <a href="../privacidad/" target="_blank">Ver política</a>.</span></label><label class="check"><input name="marketingConsent" type="checkbox"><span>Acepto recibir comunicaciones comerciales y mensajes por WhatsApp.</span></label><p class="notice">Pago por Nequi: <b>${escapeHtml(active.nequiNumber||"se indicará al confirmar")}</b><br>${escapeHtml(active.paymentInstructions||"Conserva el comprobante para la validación manual.")}</p><button class="primary">Registrar participación</button><p class="error" id="form-error"></p></form>`;participationContent.querySelector("#participant-form").addEventListener("submit",submit);participation.showModal()}
async function submit(event){event.preventDefault();const form=new FormData(event.currentTarget);const errorNode=participationContent.querySelector("#form-error");try{const receipt=await upload("payment_receipt",form.get("receipt"));const participantPhoto=await upload("participant_photo",form.get("participantPhoto"));const payload={action:"submit",reservationId:reservation.id,reservationCode:reservation.code,fullName:form.get("fullName"),phone:form.get("phone"),email:form.get("email"),city:form.get("city"),paymentReference:form.get("paymentReference"),reportedAmount:form.get("reportedAmount"),paidAt:form.get("paidAt"),observations:form.get("observations"),receipt,participantPhoto,consent:form.get("consent")==="on",marketingConsent:form.get("marketingConsent")==="on",website:""};await api("POST",payload);participationContent.innerHTML=`<h2>Registro recibido</h2><p class="notice">Tu participación queda pendiente de validación. Conserva tu comprobante y utiliza el código de reserva <b>${escapeHtml(reservation.code)}</b> cuando necesites soporte.</p><div class="payment-step"><h3>Pago por Nequi</h3><p>Envía ${money.format(selected.length*active.priceCop)} a ${escapeHtml(active.nequiNumber||"el número indicado por CRK")}.</p><div class="copy-row"><code>${escapeHtml(active.nequiNumber||"")}</code><button type="button" data-copy="${escapeHtml(active.nequiNumber||"")}">Copiar</button></div><a class="primary" href="https://wa.me/573028402389?text=${encodeURIComponent(`Sorteo ${active.title}. Participante: ${payload.fullName}. Números: ${selected.map(n=>String(n).padStart(2,"0")).join(", ")}. Valor: ${money.format(selected.length*active.priceCop)}. Reserva: ${reservation.code}`)}" target="_blank" rel="noopener">Enviar mensaje</a></div>`;participationContent.querySelector("[data-copy]")?.addEventListener("click",async(e)=>{await navigator.clipboard.writeText(e.currentTarget.dataset.copy||"");e.currentTarget.textContent="Copiado"});await load()}catch(error){errorNode.textContent=error.message}}
async function load(){try{const data=await api("GET");raffles=data.raffles||[];render()}catch(error){list.innerHTML=`<p class="empty">${error.message}</p>`}}load();
