import { adminClient, allowedOrigin, cleanText, corsHeaders, json, readBodyLimited, requireCrmOwner } from "../_shared/backend.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const integer = (value: unknown, min: number, max: number, fallback?: number) => { const result = Number(value); return Number.isInteger(result) && result >= min && result <= max ? result : fallback; };
const validStatus = new Set(["draft","upcoming","active","sold_out","finished","archived"]);

function rafflePayload(data: Record<string, unknown>) {
  const title = cleanText(data.title, 140); const slug = cleanText(data.slug, 80).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
  const description = cleanText(data.description, 3000); const prizeName = cleanText(data.prizeName, 160); const status = cleanText(data.status, 20);
  const price = integer(data.priceCop, 0, 999999999); const maximum = integer(data.maxNumbersPerParticipant, 1, 100, 1); const numberCount = integer(data.numberCount, 1, 1000, 100); const minutes = integer(data.reservationMinutes, 5, 120, 20);
  if (title.length < 2 || !slug || description.length < 2 || prizeName.length < 2 || price === undefined || !validStatus.has(status)) return null;
  const bannerPath = cleanText(data.bannerPath, 500); const prizeImagePath = cleanText(data.prizeImagePath, 500);
  if ((bannerPath && !bannerPath.startsWith("admin/")) || (prizeImagePath && !prizeImagePath.startsWith("admin/"))) return null;
  return { title, slug, description, prize_name: prizeName, legal_type: ["raffle","promotional_draw","voluntary_donation","participation_sale"].includes(String(data.legalType)) ? data.legalType : "raffle", status, price_cop: price, max_numbers_per_participant: maximum, number_count: numberCount, reservation_minutes: minutes, banner_path: bannerPath || null, prize_image_path: prizeImagePath || null, nequi_number: cleanText(data.nequiNumber, 30) || null, payment_instructions: cleanText(data.paymentInstructions, 2000), terms_text: cleanText(data.termsText, 10000), terms_version: cleanText(data.termsVersion, 40) || "v1", privacy_text: cleanText(data.privacyText, 2000) || "Autorizo el tratamiento de mis datos personales conforme a la política de tratamiento de datos.", privacy_version: cleanText(data.privacyVersion, 40) || "v1", starts_at: data.startsAt ? new Date(String(data.startsAt)).toISOString() : null, closes_at: data.closesAt ? new Date(String(data.closesAt)).toISOString() : null, draw_at: data.drawAt ? new Date(String(data.drawAt)).toISOString() : null };
}

async function dashboard() {
  const client = adminClient(); await client.rpc("release_expired_raffle_reservations", { p_raffle_id: null });
  const raffles = await client.from("raffles").select("*").is("archived_at", null).order("created_at", { ascending: false }); if (raffles.error) throw raffles.error;
  const ids = (raffles.data || []).map((item) => item.id); const numbers = ids.length ? await client.from("raffle_numbers").select("raffle_id,number,state,participant_id").in("raffle_id", ids) : { data: [], error: null }; if (numbers.error) throw numbers.error;
  const participants = ids.length ? await client.from("raffle_participants").select("*,raffles(title,slug)").in("raffle_id", ids).order("created_at", { ascending: false }).limit(500) : { data: [], error: null }; if (participants.error) throw participants.error;
  const enriched = (participants.data || []).map((participant) => ({ ...participant, numbers: (numbers.data || []).filter((number) => number.participant_id === participant.id).map((number) => number.number).sort((a,b)=>a-b) }));
  const stats = (raffles.data || []).map((raffle) => { const values=(numbers.data||[]).filter((number)=>number.raffle_id===raffle.id); const paid=values.filter(v=>["paid","winner"].includes(v.state)).length; return { raffleId:raffle.id,total:Number(raffle.number_count || values.length),available:values.filter(v=>v.state==="available").length,reserved:values.filter(v=>v.state==="reserved").length,pending:values.filter(v=>v.state==="pending_validation").length,paid,percentage:values.length ? Math.round(paid*100/values.length) : 0 }; });
  const paths = [...(raffles.data || []).flatMap((raffle) => [raffle.banner_path, raffle.prize_image_path]), ...enriched.flatMap((participant) => [participant.participant_photo_path, participant.receipt_path])].filter((path): path is string => typeof path === "string" && path.length > 0);
  const signed = paths.length ? await client.storage.from("raffle-private").createSignedUrls([...new Set(paths)], 900) : { data: [], error: null }; if (signed.error) throw signed.error;
  const urls = new Map((signed.data || []).filter((item) => item.path && item.signedUrl).map((item) => [item.path, item.signedUrl]));
  return { raffles: (raffles.data || []).map((raffle) => ({ ...raffle, banner_url: urls.get(raffle.banner_path || "") || "", prize_image_url: urls.get(raffle.prize_image_path || "") || "" })), participants: enriched.map((participant) => ({ ...participant, participant_photo_url: urls.get(participant.participant_photo_path || "") || "", receipt_url: urls.get(participant.receipt_path || "") || "" })), stats };
}

async function updateParticipant(data: Record<string, unknown>, ownerId: string) {
  const id=String(data.participantId||"");const action=cleanText(data.action,32);if(!UUID.test(id)||!["approve","reject","release","winner","note"].includes(action))return {error:"Acción inválida",status:422};
  const client=adminClient();const participant=await client.from("raffle_participants").select("*").eq("id",id).maybeSingle();if(participant.error)throw participant.error;if(!participant.data)return {error:"Participante no encontrado",status:404};
  const before=participant.data;let patch:Record<string,unknown>={};
  if(action==="approve")patch={payment_status:"approved",participation_status:"confirmed",validated_at:new Date().toISOString(),validated_by:ownerId};
  if(action==="reject")patch={payment_status:"rejected",participation_status:"cancelled",validated_at:new Date().toISOString(),validated_by:ownerId};
  if(action==="release")patch={payment_status:"rejected",participation_status:"cancelled",validated_at:new Date().toISOString(),validated_by:ownerId};
  if(action==="note")patch={internal_notes:cleanText(data.note,2000)};
  if(action==="winner")patch={participation_status:"winner"};
  const updated=await client.from("raffle_participants").update(patch).eq("id",id).select().single();if(updated.error)throw updated.error;
  if(action==="approve")await client.from("raffle_numbers").update({state:"paid",updated_at:new Date().toISOString()}).eq("participant_id",id).eq("state","pending_validation");
  if(["reject","release"].includes(action)){await client.from("raffle_numbers").update({state:"available",participant_id:null,reservation_id:null,updated_at:new Date().toISOString()}).eq("participant_id",id);}
  if(action==="winner"){const numbers=await client.from("raffle_numbers").select("number").eq("participant_id",id).eq("state","paid").limit(1);const winnerNumber=numbers.data?.[0]?.number;if(winnerNumber===undefined)return {error:"Solo se puede elegir entre participaciones aprobadas",status:409};await client.from("raffle_numbers").update({state:"winner"}).eq("participant_id",id).eq("number",winnerNumber);await client.from("raffles").update({winner_participant_id:id,winner_number:winnerNumber,winner_drawn_at:new Date().toISOString(),winner_drawn_by:ownerId,winner_published:false,status:"finished",winner_evidence:{mechanism:"manual_audited_selection",eligible_numbers:(await client.from("raffle_numbers").select("number").eq("raffle_id",participant.data.raffle_id).eq("state","paid")).data||[]}}).eq("id",participant.data.raffle_id).is("winner_participant_id",null);}
  await client.from("raffle_audit_log").insert({raffle_id:participant.data.raffle_id,participant_id:id,actor_id:ownerId,action:`participant_${action}`,before_data:before,after_data:updated.data});
  return {data:updated.data};
}

Deno.serve(async(request)=>{const origin=allowedOrigin(request);const cors=corsHeaders(origin);if(request.method==="OPTIONS")return origin?new Response(null,{status:204,headers:cors}):json({error:"Origen no permitido"},403);if(request.method!=="POST"||!origin)return json({error:"Solicitud no permitida"},403,cors);try{const auth=await requireCrmOwner(request);if(auth.error)return json({error:auth.error.message},auth.error.status,cors);const bytes=await readBodyLimited(request,65536);if(!bytes)return json({error:"Solicitud demasiado grande"},413,cors);const input:unknown=JSON.parse(new TextDecoder().decode(bytes));if(!object(input))return json({error:"Solicitud inválida"},422,cors);const action=cleanText(input.action,40);if(action==="dashboard")return json(await dashboard(),200,cors);if(action==="save_raffle"){const values=rafflePayload(input);if(!values)return json({error:"Revisa los campos del sorteo"},422,cors);const id=String(input.id||"");const client=adminClient();const result=UUID.test(id)?await client.from("raffles").update({...values,updated_by:auth.owner.userId}).eq("id",id).select().single():await client.from("raffles").insert({...values,created_by:auth.owner.userId,updated_by:auth.owner.userId}).select().single();if(result.error)throw result.error;await client.from("raffle_audit_log").insert({raffle_id:result.data.id,actor_id:auth.owner.userId,action:UUID.test(id)?"raffle_updated":"raffle_created",after_data:result.data});return json({raffle:result.data},201,cors)}if(action==="participant_action"){const outcome=await updateParticipant(input,auth.owner.userId);return json(outcome,outcome.status||200,cors)}return json({error:"Acción inválida"},422,cors)}catch(error){console.error("raffle-admin",error instanceof Error?error.message:"unknown");return json({error:"No fue posible procesar la solicitud"},500,cors)}});
